apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-test-d
  labels:
    app: new_test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newtest
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: newtest
    spec:
      containers:
        - name: newtest
          image: docker.io/rictrindade/simple-flask:latest
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
